Update update-readme.yml

diff --git a/.github/workflows/update-readme.yml b/.github/workflows/update-readme.yml
--- a/.github/workflows/update-readme.yml
+++ b/.github/workflows/update-readme.yml
@@ -15,14 +15,12 @@ jobs:
 
       - name: Generate GitHub Stats
         run: |
-          curl -o github-stats.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=${{ github.actor }}&layout=compact&theme=radical&count_private=true&token=${{ secrets.GH_STATS_TOKEN }}"
+          curl -o github-stats.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=${{ github.repository_owner }}&layout=compact&theme=radical&count_private=true&token=${{ secrets.GH_STATS_TOKEN }}"
 
       - name: Commit and Push
         run: |
+          set -e  # Stop the script if any command fails
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git pull --rebase origin main  # pulls the latest changes
           git add github-stats.svg
-          git diff --quiet && echo "No changes to commit" || git commit -m "update github stats"
-          git push origin main
-
+          git diff --exit-code || (git commit -m "update github stats" && git pull --rebase && git push)
